apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platinumsequence-ingress
  namespace: platinumsequence
  annotations:
    kubernetes.io/ingress.class: "gce"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.allow-http: "true"
spec:
  tls:
  - hosts:
    - platinumsequence.com
    - www.platinumsequence.com
    secretName: platinumsequence-tls
  rules:
  - host: platinumsequence.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: www.platinumsequence.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80

